// ============================================================
// 默认简历数据：全部留空，由使用者在插件弹窗中自行填写。
// 数据仅保存在本机浏览器（chrome.storage.local），不会上传。
// ============================================================
(function () {
  const G = (typeof window !== "undefined") ? window : self;
  G.JIANLI_DEFAULTS = {
    resumeData: {
      name: "",
      gender: "",
      phone: "",
      email: "",
      birth: "",
      height: "",
      weight: "",
      hometown: "",
      graduate_status: "",
      english_level: "",
      student_cadre: "",
      id_number: "",
      political: "",
      nationality: "",
      country: "",
      current_residence: "",
      recruit_source: "",
      emergency_contact: "",
      emergency_phone: "",
      school: "",
      degree: "",
      major: "",
      major_category: "",
      graduate_year: "",
      college: "",
      education_period: "",
      grade_ranking: "",
      gpa: "",
      thesis_title: "",
      research_topic: "",
      lab: "",
      advisor: "",
      education: "",
      city: "",
      position: "",
      salary: "",
      job_type: "",
      intro: "",
      internship_position: "",
      campus_position: "",
      skills: "",
      awards: "",
      internship: "",
      work: "",
      project: "",
      patent: "",
      paper: "",
      monograph: "",
      language: "",
      english_score: "",
      certificate: "",
      portfolio: "",
      hobby: "",
    },
    settings: { autoFill: false }
  };
})();